//USER
export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

//BUSINESS
export const GET_BUSINESSES = "GET_BUSINESSES";
export const GET_BUSINESS_DETAILS = "GET_BUSINESS_DETAILS";
